### PR TITLE
fix: search inside kind tag

### PR DESCRIPTION
**Pull request by reliut-g**
If you selected the "**classic**" tag, the "**classic**" value is added to search, but then if you want to search for projects within the "**classic**" tag, You can't, because when you type, it searches all projects and/or ideas. 

### BEFORE

https://user-images.githubusercontent.com/63687573/131397999-3dd09101-40d3-4fd4-bb9c-947f74a27839.mp4

### AFTER

https://user-images.githubusercontent.com/63687573/131398015-08485c52-34e7-4935-a3d8-4c3089c0ae64.mp4

### CODE REVIEW

**Comment by ming-tsai** [comment]
Hi @reliut-g,
Please make the below suggestions:
- We could not use `history` mode, due to Netlify not understand the path, navigate this page without history mode on a new tab `https://deploy-preview-37--ideashub.netlify.app/ideas/web-app`
- Actually when I typed `web app` on the page it search the text the list with `web-app` or `web app` but now in this change this feature is not working

**Comment by reliut-g** [comment]
> * https://deploy-preview-37--ideashub.netlify.app/ideas/web-app

@ming-tsai Hi, thanks for the reminder, I've fixed it.

**Comment by ming-tsai** [comment]
> > * https://deploy-preview-37--ideashub.netlify.app/ideas/web-app
> 
> @ming-tsai Hi, thanks for the reminder, I've fixed it.

Nice

**Comment by ming-tsai** [comment]
Could you rollback the `Links` array changed, or make an object array as this?
```json
[
   {
      link: "",
      display: ""
   }
]
```

**Comment by ming-tsai** [comment]
Only has to fix the `Actually when I typed web app on the page it search the text the list with web-app or web app but now in this change this feature is not working`

**Comment by reliut-g** [comment]
> Only has to fix the `Actually when I typed web app on the page it search the text the list with web-app or web app but now in this change this feature is not working`

So you can search by tag   "web-app" or "web app"?

**Comment by ming-tsai** [comment]
> > Only has to fix the `Actually when I typed web app on the page it search the text the list with web-app or web app but now in this change this feature is not working`
> 
> So you can search by tag "web-app" or "web app"?
> 
> if you search for "web app", the result is correct.

Yes

**Comment by reliut-g** [comment]
> > > Only has to fix the `Actually when I typed web app on the page it search the text the list with web-app or web app but now in this change this feature is not working`
> > 
> > 
> > So you can search by tag "web-app" or "web app"?
> > if you search for "web app", the result is correct.
> 
> Yes

Done!

**Review by ming-tsai — APPROVED** [review]

**Review by ming-tsai — APPROVED** [review]
Nice work!!!

**Pull request merged**
