### PR TITLE
docs(projects): add pokemon awesome

### PR DESCRIPTION
**Pull request by shonenxnaifu**

### CODE REVIEW

**Comment by ahmedsilat44** [comment]
I think you should also update docs accordingly. Like if your project is website intermediate add your project to docs/WEBSITE_INTERMEDIATE.md

**Comment by shonenxnaifu** [comment]
> I think you should also update docs accordingly. Like if your project is website intermediate add your project to docs/WEBSITE_INTERMEDIATE.md

thanks for your suggestion, i will update the docs soon

**Review by ming-tsai — APPROVED** [review]

**Comment by ahmedsilat44** [comment]
> i'm already added new website category and fixed merge confilct kindly check my pr @ahmedsilat44 

I can't do that I am just a random contributor 😂

**Comment by shonenxnaifu** [comment]
sorry 😂 i thought you were a maintainer

**Comment by shonenxnaifu** [comment]
> > i'm already added new website category and fixed merge confilct kindly check my pr @ahmedsilat44
> 
> I can't do that I am just a random contributor 😂


sorry 😂 i thought you were a maintainer @ahmedsilat44

**Pull request merged**
